[general]
import = ["~/.config/alacritty/tokyonight_night.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 1.0

[window.padding] 
x = 5
y = 5

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 1
