# See config properties here https://alacritty.org/config-alacritty.html
live_config_reload=true

[window]
dimensions={columns=100, lines=50}
position={x=0, y=0}
padding={x=10, y=10}
dynamic_padding=true
decorations="None"
opacity=0.9
# works only on wayland and macos
blur=true
startup_mode="Windowed"
title="Alacirtty Terminal"
dynamic_title=true
class={instance="alacritty", general="Alacritty"}
decorations_theme_variant="Dark"
resize_increments=false

[scrolling]
history = 5000
multiplier = 3

[font]
size = 12

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
blink_interval = 1000
unfocused_hollow = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"
