return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "html",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "tsx",
            "typescript",
            "tailwind",
            "vim",
            "css",
            "java",
            "jsx",
            "yaml",
        },
        indent = { enable = true },
        highlight = { enable = true },
        folds = { enable = true },
    },
}
